[build.environment]
  BUN_VERSION = "1.2.4" # Sesuaikan dengan versi Bun yang ingin Anda gunakan

[build]
  command = "bun install && bun run build"
  publish = "dist" # Sesuaikan dengan direktori output build Anda (misalnya "dist", "build", "public")